export const COLOR_NAMES = [
  { name: "Abbey", hex: "#4C4F56" },
  { name: "Absolute Zero", hex: "#0048BA" },
  { name: "Acadia", hex: "#1B1404" },
  { name: "Acapulco", hex: "#7CB0A1" },
  { name: "Acid Green", hex: "#8FFE09" },
  { name: "Adobe", hex: "#BD6C48" },
  { name: "Aero Blue", hex: "#C9FFE5" },
  { name: "Affair", hex: "#714693" },
  { name: "Agate Grey", hex: "#B5B8B1" },
  { name: "Akaroa", hex: "#D4C4A8" },
  { name: "Alabaster", hex: "#FAFAFA" },
  { name: "Alizarin Crimson", hex: "#E32636" },
  { name: "Allegheny River", hex: "#4F666A" },
  { name: "Almond", hex: "#EFDECD" },
  { name: "Alpine", hex: "#AF8F2C" },
  { name: "Aluminium", hex: "#A9ACB6" },
  { name: "Amaranth", hex: "#E52B50" },
  { name: "Amazon", hex: "#3B7A57" },
  { name: "Amber", hex: "#FFBF00" },
  { name: "American Rose", hex: "#FF033E" },
  { name: "Amethyst", hex: "#9966CC" },
  { name: "Anti-Flash White", hex: "#F2F3F4" },
  { name: "Antique Brass", hex: "#CD9575" },
  { name: "Antique Bronze", hex: "#665D1E" },
  { name: "Antique Fuchsia", hex: "#915C83" },
  { name: "Antique White", hex: "#FAEBD7" },
  { name: "Anzac", hex: "#E0B646" },
  { name: "Ao", hex: "#008000" },
  { name: "Apple", hex: "#4FA83D" },
  { name: "Apple Blossom", hex: "#AF4D43" },
  { name: "Apple Green", hex: "#8DB600" },
  { name: "Apricot", hex: "#FBCEB1" },
  { name: "Aqua", hex: "#00FFFF" },
  { name: "Aquamarine", hex: "#7FFFD4" },
  { name: "Arctic Lime", hex: "#D0FF14" },
  { name: "Army Green", hex: "#4B5320" },
  { name: "Artichoke", hex: "#8F9779" },
  { name: "Arylide Yellow", hex: "#E9D66B" },
  { name: "Ash Grey", hex: "#B2BEB5" },
  { name: "Asparagus", hex: "#87A96B" },
  { name: "Atomic Tangerine", hex: "#FF9966" },
  { name: "Auburn", hex: "#A52A2A" },
  { name: "Aureolin", hex: "#FDEE00" },
  { name: "Aurometalasaurus", hex: "#6E7F80" },
  { name: "Avocado", hex: "#568203" },
  { name: "Awesome", hex: "#FF2052" },
  { name: "Aztec", hex: "#0D1C19" },
  { name: "Azure", hex: "#007FFF" },
  { name: "Azure Mist", hex: "#F0FFFF" },
  { name: "Baby Blue", hex: "#89CFF0" },
  { name: "Baby Pink", hex: "#F4C2C2" },
  { name: "Bamboo", hex: "#DA6304" },
  { name: "Banana Mania", hex: "#FAE7B5" },
  { name: "Banana Yellow", hex: "#FFE135" },
  { name: "Barley White", hex: "#FFF4CE" },
  { name: "Barossa", hex: "#44012D" },
  { name: "Bastille", hex: "#292130" },
  { name: "Battleship Grey", hex: "#848482" },
  { name: "Bay Leaf", hex: "#7DA98D" },
  { name: "Bean Red", hex: "#F75D59" },
  { name: "Bear Brown", hex: "#63473B" },
  { name: "Beaver", hex: "#9F8170" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Bermuda", hex: "#7DD1C1" },
  { name: "Beryl Green", hex: "#DEE5C0" },
  { name: "Bianca", hex: "#FCFBF3" },
  { name: "Big Dip O’ruby", hex: "#9C2542" },
  { name: "Biloba Flower", hex: "#B2A1EA" },
  { name: "Birch", hex: "#373021" },
  { name: "Biscay", hex: "#1B3162" },
  { name: "Bismark", hex: "#497183" },
  { name: "Bison Hide", hex: "#C1B7A4" },
  { name: "Bitter Lemon", hex: "#CAE00D" },
  { name: "Bittersweet", hex: "#FE6F5E" },
  { name: "Black", hex: "#000000" },
  { name: "Black Bean", hex: "#3D0C02" },
  { name: "Black Forest", hex: "#0B1304" },
  { name: "Black Olive", hex: "#3B3C36" },
  { name: "Black Rose", hex: "#67032D" },
  { name: "Blanched Almond", hex: "#FFEBCD" },
  { name: "Blast-Off Bronze", hex: "#A57164" },
  { name: "Blaze Orange", hex: "#FF6700" },
  { name: "Bleach White", hex: "#FEF3D8" },
  { name: "Bleached Cedar", hex: "#2C2133" },
  { name: "Blizzard Blue", hex: "#ACE5EE" },
  { name: "Blond", hex: "#FAF0BE" },
  { name: "Blood", hex: "#830303" },
  { name: "Blossom", hex: "#DCB4BC" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Blue Bell", hex: "#A2A2D0" },
  { name: "Blue Chalk", hex: "#F1E9FF" },
  { name: "Blue Diamond", hex: "#380473" },
  { name: "Blue Lagoon", hex: "#00626F" },
  { name: "Blue Marguerite", hex: "#7666C6" },
  { name: "Blue Ribbon", hex: "#0066FF" },
  { name: "Blue Whale", hex: "#042E4C" },
  { name: "Blue Zodiac", hex: "#13264D" },
  { name: "Blueberry", hex: "#4F86F7" },
  { name: "Blush", hex: "#B44668" },
  { name: "Blush Pink", hex: "#FF6FFF" },
];
